<?php

namespace AppBundle\Repository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWords($search)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $regExString = $this->generateRegEx($search);

        $query = $qb->select('w')
                ->from('AppBundle:Word', 'w')
                ->andWhere('REGEXP(w.word, :regexp) = true')
                    ->setParameter('regexp', $regExString)
                    ->setMaxResults(10000)
                ->getQuery()->getResult();

        try {

            return $query;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function generateRegEx($searchWord)
    {
        $regexString = "^";

        for ($i = 0; $i < strlen($searchWord); $i++) {
            if ($searchWord[$i] == "-") {
                $regexString .= '.';
            } else {
                $regexString .= $searchWord[$i];
            }
        }
        $regexString .= '$';
        return $regexString;
    }
}
